general:
  debug: false
  disabled-worlds: []
  max-broken-blocks: 128

effects:
  autosmelt: { enabled: true }
  telekinesis: { enabled: true }
  veinminer:
    enabled: true
    ores:
      - COAL_ORE
      - IRON_ORE
      - COPPER_ORE
      - GOLD_ORE
      - LAPIS_ORE
      - REDSTONE_ORE
      - DIAMOND_ORE
      - EMERALD_ORE
      - NETHER_QUARTZ_ORE
      - NETHER_GOLD_ORE
      - DEEPSLATE_COAL_ORE
      - DEEPSLATE_IRON_ORE
      - DEEPSLATE_COPPER_ORE
      - DEEPSLATE_GOLD_ORE
      - DEEPSLATE_LAPIS_ORE
      - DEEPSLATE_REDSTONE_ORE
      - DEEPSLATE_DIAMOND_ORE
      - DEEPSLATE_EMERALD_ORE
  areaminer: { enabled: true, radius: 1 }
  lifesteal: { enabled: true, heal-percentage-per-level: 0.05 }
  wither: { enabled: true, duration-ticks-per-level: 40, amplifier: 0, chance: 0.25 }
  frozen: { enabled: true, duration-ticks-per-level: 40, amplifier: 0, chance: 0.25 }
  doublestrike: { enabled: true, chance-per-level: 0.15 }
  gears: { enabled: true, speed-amplifier-per-level: 0 }
  haste_touch: { enabled: true, haste-amplifier-per-level: 0 }
  night_vision: { enabled: true }
  magnet: { enabled: true, range-per-level: 3, max-range: 10 }
  xp_boost: { enabled: true, multiplier-per-level: 0.25 }

specialitems:
  harvester_scale: 0.25
  vein_scale: 0.20
  min_total_floor: true
  fortune_interaction: "ignore"
  yield_bonus_attr_key: "si.yield_bonus"

farmxmine:
  direct_to_inventory: true
