name: SpecialItems
main: com.specialitems.SpecialItemsPlugin
version: 1.2.0
api-version: '1.21'
author: You
commands:
  si:
    description: SpecialItems command
    usage: /si
  bin:
    description: View deleted special items (admin)
    usage: /bin
    permission: specialitems.admin
permissions:
  specialitems.admin:
    description: Allows using admin SpecialItems subcommands
    default: op
