name: SpecialItems
main: com.specialitems.SpecialItemsPlugin
version: 1.2.2
api-version: 1.21
author: You
commands:
  si:
    description: SpecialItems command
    usage: /si
  bin:
    description: View deleted special items (admin)
    usage: /bin
    permission: specialitems.admin
  si_givecmd:
    description: Give a test item with CustomModelData
    usage: /si_givecmd <material> <cmd>
    permission: specialitems.debug
  si_cmdcheck:
    description: Show CustomModelData of the held item
    usage: /si_cmdcheck
    permission: specialitems.debug
  si_cmdfix:
    description: Normalize held item CustomModelData to integer
    usage: /si_cmdfix
    permission: specialitems.debug
  cmdprobe:
    description: Give an item with explicit CustomModelData
    usage: /cmdprobe <material> <cmd>
    permission: specialitems.debug
  cmdscan:
    description: Scan open GUI for missing or mismatched CMD
    usage: /cmdscan
    permission: specialitems.debug
permissions:
  specialitems.admin:
    description: Allows using admin SpecialItems subcommands
    default: op
  specialitems.debug:
    default: op
