general:
  respawn_seconds: 20
  main_world: "world"
  override_cancelled: true
mining:
  enabled: true
  require_tool: PICKAXE
  ores: [COAL_ORE, IRON_ORE, GOLD_ORE, REDSTONE_ORE, LAPIS_ORE, COPPER_ORE, DIAMOND_ORE, EMERALD_ORE, NETHER_QUARTZ_ORE,
         DEEPSLATE_COAL_ORE, DEEPSLATE_IRON_ORE, DEEPSLATE_GOLD_ORE, DEEPSLATE_REDSTONE_ORE, DEEPSLATE_LAPIS_ORE,
         DEEPSLATE_COPPER_ORE, DEEPSLATE_DIAMOND_ORE, DEEPSLATE_EMERALD_ORE]
farming:
  enabled: true
  require_tool: HOE
  crops: [WHEAT, CARROTS, POTATOES, BEETROOTS]
leveling:
  xp_per_harvest:
    mine: 3
    farm: 1
  base_xp_per_level: 100
  xp_growth_per_level: 25
