name: FarmXMine2
main: com.farmxmine2.FarmXMine2Plugin
version: 0.1.0
api-version: "1.21"
author: "FarmXMine Team"
softdepend: [PlaceholderAPI]
commands:
  fm2:
    description: FarmXMine2 commands
    usage: /fm2 <reload|level>
    permission: farmxmine2.level
permissions:
  farmxmine2.level:
    default: true
  farmxmine2.admin:
    default: op
