display_base_item: CARROT_ON_A_STICK
slots:
  HEAD:
    offset:
      x: 0.0
      y: 0.0
      z: 0.0
      yaw: 0.0
      pitch: 0.0
      roll: 0.0
      scale: 1.0
    models:
      1000: default_head
  CHEST:
    offset:
      x: 0.0
      y: 0.0
      z: 0.0
      yaw: 0.0
      pitch: 0.0
      roll: 0.0
      scale: 1.0
    models:
      1000: default_chest
  LEGS:
    offset:
      x: 0.0
      y: 0.0
      z: 0.0
      yaw: 0.0
      pitch: 0.0
      roll: 0.0
      scale: 1.0
    models:
      1000: default_legs
  FEET:
    offset:
      x: 0.0
      y: 0.0
      z: 0.0
      yaw: 0.0
      pitch: 0.0
      roll: 0.0
      scale: 1.0
    models:
      1000: default_feet
