crates:
  PRESTIGE:
    display: "&d&lPrestige Crate"
    key:
      display: "&dPrestige Key"
      material: TRIPWIRE_HOOK
      custom_model_data: 21001
    open-method: BLOCK # BLOCK or GUI
    rewards:

      # ===== SCHWÄCHERE SPECIAL ITEMS (~7% je) =====
      - id: "si_weak_stone_miner"
        weight: 7   # 7%
        type: COMMAND
        commands:
          - "si give {player} stone_miner"
        display:
          material: IRON_PICKAXE
          name: "&7Stonebreaker"
          lore:
            - "&7Small AoE for early mining."

      - id: "si_weak_novice_farmer"
        weight: 7   # 7%
        type: COMMAND
        commands:
          - "si give {player} novice_farmer"
        display:
          material: DIAMOND_HOE
          name: "&aSprout Hoe"
          lore:
            - "&7Harvests a small area and replants."

      - id: "si_weak_rookie_boots"
        weight: 7   # 7%
        type: COMMAND
        commands:
          - "si give {player} rookie_scout_boots"
        display:
          material: IRON_BOOTS
          name: "&bLightfoot Boots"
          lore:
            - "&7A touch of speed and pull."

      - id: "si_weak_cave_lantern"
        weight: 7   # 7%
        type: COMMAND
        commands:
          - "si give {player} cave_lantern_helm"
        display:
          material: IRON_HELMET
          name: "&eCave Lantern"
          lore:
            - "&7Keeps your vision bright underground."

      # ===== MITTELSTARKE SPECIAL ITEMS (~3% je) =====
      - id: "si_mid_miner_pick_t2"
        weight: 3   # 3%
        type: COMMAND
        commands:
          - "si give {player} miner_pick_t2"
        display:
          material: NETHERITE_PICKAXE
          name: "&6Vein Ripper II"
          lore:
            - "&7Bigger veins, faster progress."
            - "&7+ Telekinesis"

      - id: "si_mid_farmer_hoe_t2"
        weight: 3   # 3%
        type: COMMAND
        commands:
          - "si give {player} farmer_hoe_t2"
        display:
          material: NETHERITE_HOE
          name: "&aGreen Reaper II"
          lore:
            - "&75x5 harvest & auto-replant."

      - id: "si_mid_hunter_sword_t2"
        weight: 3   # 3%
        type: COMMAND
        commands:
          - "si give {player} hunter_sword_t2"
        display:
          material: NETHERITE_SWORD
          name: "&cVampire Edge II"
          lore:
            - "&7Lifesteal + chance for a second strike."

      - id: "si_mid_scout_boots_t2"
        weight: 3   # 3%
        type: COMMAND
        commands:
          - "si give {player} scout_boots_t2"
        display:
          material: NETHERITE_BOOTS
          name: "&bWindrunner II"
          lore:
            - "&7Faster movement & item pull."

      # ===== 32 DIAMANTEN (~8%) =====
      - id: "diamonds_32"
        weight: 8   # 8%
        type: ITEM
        amount: 32
        item:
          material: DIAMOND
          name: "&b32x Diamonds"
          lore:
            - "&7A solid stack of wealth."

      # ===== EXISTIERENDE & SICHERE REWARDS (REST = 47%) =====
      - id: "money_boost_2x_1h"
        weight: 12  # 12%
        type: COMMAND
        commands:
          - "lp user {player} permission settemp lootfactory.boost.yield.2x true 1h"
        display:
          material: GOLD_INGOT
          name: "&6&l2x Yield Booster (1h)"
          lore:
            - "&7Doubles your factory yield for 1 hour."
            - "&8Granted via permission."
          custom_model_data: 22001

      - id: "money_xp_bundle"
        weight: 25  # 25%
        type: MONEY_XP
        money: 25000.0
        xp: 500
        display:
          material: EMERALD
          name: "&a$25,000 &7+ &b500 XP"
          lore:
            - "&7Immediate deposit to your balance."
            - "&7And factory player XP."
          custom_model_data: 22002

      - id: "prestige_key_x2"
        weight: 8   # 8%
        type: KEY
        key:
          crate: "PRESTIGE"
          amount: 2
        display:
          material: TRIPWIRE_HOOK
          name: "&dPrestige Keys x2"
          lore:
            - "&7Open the Prestige Crate two more times!"
          custom_model_data: 21001

      - id: "emeralds_16"
        weight: 2   # 2%
        type: ITEM
        amount: 16
        item:
          material: EMERALD
          name: "&a16x Emeralds"
          lore:
            - "&7Useful for trading."

  LEGENDARY:
    display: "&6&lLegendary Crate"
    key:
      display: "&6Legendary Key"
      material: TRIPWIRE_HOOK
      custom_model_data: 21002
    open-method: GUI # BLOCK or GUI
    rewards:
      - id: "small_money_bundle"
        weight: 40
        type: MONEY_XP
        money: 10000.0
        xp: 250
        display:
          material: GOLD_INGOT
          name: "&e$10,000 &7+ &b250 XP"
          lore:
            - "&7A helpful boost to your balance."
            - "&7And some factory XP."
          custom_model_data: 22003

      - id: "legendary_sword"
        weight: 5
        type: ITEM
        amount: 1
        item:
          material: DIAMOND_SWORD
          name: "&6&lLegendary Sword"
          lore:
            - "&7Forged for true champions."
          custom_model_data: 31002
          enchantments:
            - "DAMAGE_ALL:5"
            - "DURABILITY:3"

      - id: "prestige_key_x2"
        weight: 8
        type: KEY
        key:
          crate: "PRESTIGE"
          amount: 2
        display:
          material: TRIPWIRE_HOOK
          name: "&dPrestige Keys x2"
          lore:
            - "&7Open the Prestige Crate two more times!"
          custom_model_data: 21001
  LEGENDARY:
    display: "&6&lLegendary Crate"
    key:
      display: "&6Legendary Key"
      material: TRIPWIRE_HOOK
      custom_model_data: 21002
    open-method: GUI # BLOCK or GUI
    rewards:
      - id: "small_money_bundle"
        weight: 40
        type: MONEY_XP
        money: 10000.0
        xp: 250
        display:
          material: GOLD_INGOT
          name: "&e$10,000 &7+ &b250 XP"
          lore:
            - "&7A helpful boost to your balance."
            - "&7And some factory XP."
          custom_model_data: 22003
      - id: "legendary_sword"
        weight: 5
        type: ITEM
        amount: 1
        item:
          material: DIAMOND_SWORD
          name: "&6&lLegendary Sword"
          lore:
            - "&7Forged for true champions."
          custom_model_data: 31002
          enchantments:
            - "DAMAGE_ALL:5"
            - "DURABILITY:3"
      - id: "prestige_key"
        weight: 3
        type: KEY
        key:
          crate: "PRESTIGE"
          amount: 1
        display:
          material: TRIPWIRE_HOOK
          name: "&dPrestige Key"
          lore:
            - "&7Unlock the Prestige Crate!"
          custom_model_data: 21001
      - id: "fly_command"
        weight: 2
        type: COMMAND
        commands:
          - "lp user {player} permission settemp essentials.fly true 1h"
        display:
          material: FEATHER
          name: "&f&lFlight (1h)"
          lore:
            - "&7Grants temporary flight ability."
          custom_model_data: 22004
  MYTHIC:
    display: "&5&lMythic Crate"
    key:
      display: "&5Mythic Key"
      material: TRIPWIRE_HOOK
      custom_model_data: 21003
    open-method: BLOCK # BLOCK or GUI
    rewards:
      - id: "big_money_bundle"
        weight: 30
        type: MONEY_XP
        money: 50000.0
        xp: 1000
        display:
          material: EMERALD
          name: "&a$50,000 &7+ &b1,000 XP"
          lore:
            - "&7A sizable deposit to your balance."
            - "&7And lots of factory XP."
          custom_model_data: 22005
      - id: "mythic_pickaxe"
        weight: 4
        type: ITEM
        amount: 1
        item:
          material: NETHERITE_PICKAXE
          name: "&5&lMythic Pickaxe"
          lore:
            - "&7A pickaxe of mythical power."
          custom_model_data: 31003
          enchantments:
            - "DURABILITY:5"
            - "DIG_SPEED:6"
      - id: "legendary_key"
        weight: 6
        type: KEY
        key:
          crate: "LEGENDARY"
          amount: 1
        display:
          material: TRIPWIRE_HOOK
          name: "&6Legendary Key"
          lore:
            - "&7Unlock the Legendary Crate!"
          custom_model_data: 21002
      - id: "rank_command"
        weight: 1
        type: COMMAND
        commands:
          - "lp user {player} group addtemp noble 7d"
        display:
          material: PAPER
          name: "&f&lTemporary Noble Rank"
          lore:
            - "&7Grants the &fNoble &7rank for 7 days."
          custom_model_data: 22006

      - id: "prestige_key"
        weight: 3
        type: KEY
        key:
          crate: "PRESTIGE"
          amount: 1
        display:
          material: TRIPWIRE_HOOK
          name: "&dPrestige Key"
          lore:
            - "&7Unlock the Prestige Crate!"
          custom_model_data: 21001

      - id: "fly_command"
        weight: 2
        type: COMMAND
        commands:
          - "lp user {player} permission settemp essentials.fly true 1h"
        display:
          material: FEATHER
          name: "&f&lFlight (1h)"
          lore:
            - "&7Grants temporary flight ability."
          custom_model_data: 22004

  MYTHIC:
    display: "&5&lMythic Crate"
    key:
      display: "&5Mythic Key"
      material: TRIPWIRE_HOOK
      custom_model_data: 21003
    open-method: BLOCK # BLOCK or GUI
    rewards:
      - id: "big_money_bundle"
        weight: 30
        type: MONEY_XP
        money: 50000.0
        xp: 1000
        display:
          material: EMERALD
          name: "&a$50,000 &7+ &b1,000 XP"
          lore:
            - "&7A sizable deposit to your balance."
            - "&7And lots of factory XP."
          custom_model_data: 22005

      - id: "mythic_pickaxe"
        weight: 4
        type: ITEM
        amount: 1
        item:
          material: NETHERITE_PICKAXE
          name: "&5&lMythic Pickaxe"
          lore:
            - "&7A pickaxe of mythical power."
          custom_model_data: 31003
          enchantments:
            - "DURABILITY:5"
            - "DIG_SPEED:6"

      - id: "legendary_key"
        weight: 6
        type: KEY
        key:
          crate: "LEGENDARY"
          amount: 1
        display:
          material: TRIPWIRE_HOOK
          name: "&6Legendary Key"
          lore:
            - "&7Unlock the Legendary Crate!"
          custom_model_data: 21002

      - id: "rank_command"
        weight: 1
        type: COMMAND
        commands:
          - "lp user {player} group addtemp noble 7d"
        display:
          material: PAPER
          name: "&f&lTemporary Noble Rank"
          lore:
            - "&7Grants the &fNoble &7rank for 7 days."
          custom_model_data: 22006

      - id: "money_voucher_100k"
        weight: 5
        type: MONEY_XP
        money: 100000.0
        display:
          material: PAPER
          name: "&a$100,000 Voucher"
          lore:
            - "&7Immediate deposit to your balance."
          custom_model_data: 22003

      # Examples of Special Items (from SpecialItems templates)
      - id: "si_stone_miner"
        weight: 15
        type: SPECIAL_ITEM
        template: "stone_miner"

      - id: "si_novice_farmer"
        weight: 15
        type: SPECIAL_ITEM
        template: "novice_farmer"

      - id: "si_rookie_scout_boots"
        weight: 15
        type: SPECIAL_ITEM
        template: "rookie_scout_boots"

      - id: "si_cave_lantern_helm"
        weight: 15
        type: SPECIAL_ITEM
        template: "cave_lantern_helm"

      - id: "si_rookie_hunter"
        weight: 15
        type: SPECIAL_ITEM
        template: "rookie_hunter"

settings:
  default-gui-title: "&6Crates"
  sounds:
    open: UI_TOAST_CHALLENGE_COMPLETE
    reward: ENTITY_EXPERIENCE_ORB_PICKUP
