name: LootCrates
main: com.lootcrates.LootCratesPlugin
version: 1.2.0
api-version: '1.21'
authors: [Leon, ChatGPT]
depend: [Vault, SpecialItems]
commands:
  crate:
    description: Crate admin & player commands
    usage: /crate <open|givekey|preview|list|reload|bind|unbind>
    aliases: [lootcrates, lc]
    permission: lootcrates.use
permissions:
  lootcrates.use:
    default: true
  lootcrates.admin:
    default: op
