name: FocusNPC
main: com.focusnpc.FocusNPCPlugin
version: 1.0.0
api-version: "1.21"
softdepend: [PlaceholderAPI, Citizens, FarmXMine]
commands:
  focusnpc:
    description: Manage FocusNPCs
    usage: /focusnpc <spawn|remove|list|reload>
    permission: focusnpc.admin
permissions:
  focusnpc.admin:
    description: Allows managing FocusNPCs
    default: op
