default-slots: 2
slot-permission-prefix: "lootpets.slots."

gui:
  title: "&6Pets"
  rows: 6
  active-slot-indices:
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
  owned-range:
    start: 9
    end: 53
