debug:
  enabled: false
  categories:
    gui: false
    boosts: false
    papi: false
    storage: false
    eggs: false
    reload: false
    validator: false
  throttle_millis: 750
  inspect_max_lines: 200

storage:
  provider: "YAML"
  flush_interval_seconds: 30
  preload_on_join: true
  sqlite:
    file: "lootpets.db"
  mysql:
    host: "localhost"
    port: 3306
    database: "lootpets"
    user: "root"
    password: ""
    pool:
      size: 8
      idle_seconds: 60
  migrations:
    allow_auto_migrate: false
    backup_yaml_before_migrate: true
    verify_counts_after_migrate: true

cross_server:
  enabled: true
  poll_interval_seconds: 5
  poll_jitter_millis: 400
  max_batch_players: 200
  clock_skew_tolerance_millis: 2000
  idempotency_window_seconds: 20
  conflict:
    policy: "MERGE_PREFER_NEWER"
    server_priority: []
  heartbeat:
    enabled: true
    interval_seconds: 15
    stale_after_seconds: 60
    server_id: "AUTO"
default-slots: 2
slot-permission-prefix: "lootpets.slots."
equip-cooldown-ms: 300

leveling_runtime:
  tick_interval_seconds: 30
  xp_per_tick: 1
  xp_per_level: 60
  level_cap_base: 100
  level_cap_extra_per_star: 50

eggs:
  detection:
    strategy: PDC
    namespace: lootpets
    keys:
      type: type
      rarity: rarity
    match:
      name_prefix: "Pet Egg:"
      lore_contains: "LootPets Egg"
  consume_on_redeem: true
  redeem_block_in_creative: false
  redeem_world_blacklist: []
  redeem_cooldown_millis: 300
  sfx:
    unlocked: ""
    duplicate: ""
  messages:
    enabled: true

gui:
  title: "&6Pets"
  rows: 6
  active-slot-indices:
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
  owned-range:
    start: 9
    end: 53
  features:
    filters_enabled: true
    sorting_enabled: true
    pagination_enabled: true
    compare_enabled: true
    album_enabled: true
  pagination:
    page_size: 28
    controls: { prev_slot: 45, next_slot: 53 }
  sorting:
    default: "RARITY_DESC,STARS_DESC,LEVEL_DESC,NAME_ASC"
    modes: [ "RARITY_ASC", "RARITY_DESC", "STARS_ASC", "STARS_DESC", "LEVEL_ASC", "LEVEL_DESC", "NAME_ASC", "NAME_DESC" ]
  filters:
    rarity_filter: true
    type_filter: true
  compare:
    max_items: 2
    open_key: "SHIFT_LEFT_CLICK"

boosts:
  per_level: 0.01
  star_multiplier: 1.35
  max_stars: 5
  stacking_mode: "ADDITIVE"
  rarity_base_multipliers: {}

caps:
  global_multiplier_max: 6.0

placeholders:
  enabled: true
  format:
    percent_decimals: 0
    raw_decimals: 2
    star_symbol: "★"
    list_delimiter: ", "
    colorize_names: true

preview:
  show_types:
    - "earnings_lootfactory"
    - "earnings_sell"
  format_percent: true
  template: "{min} – {max}"
  cap_multiplier: 6.0

permission_tiers:
  enabled: false
  update_interval_seconds: 10
  node_mode: "REPLACE"
  prefix: "lootpets.tier."
  tiers:
    - { min: 1.00, max: 1.10, node: "1" }
    - { min: 1.10, max: 1.25, node: "2" }
    - { min: 1.25, max: 1.50, node: "3" }
    - { min: 1.50, max: 999.0, node: "4" }

album:
  show_unknown_greyed: true
  open_from_pets_gui: true

reload:
  enabled: true

logging:
  verbosity: "INFO"
  debug_categories: [ "papi", "boosts", "eggs", "gui" ]

shards:
  enabled: true
  overflow:
    convert_when_max_stars: true
    amounts_per_rarity: {}
    default_amount: 1
  shop:
    enabled: true
    gui:
      title: "&d&lShard Shop"
      rows: 6
      open_from_pets_gui: true
    items:
      - id: "add_evolve_1"
        type: "EVOLVE_PROGRESS"
        cost: 3
      - id: "add_xp_10"
        type: "ADD_XP"
        xp_amount: 10
        cost: 2
      - id: "rename_token"
        type: "RENAME_TOKEN"
        cost: 10
      - id: "frame_style_red"
        type: "ALBUM_FRAME"
        style: "RED"
        cost: 5
  cosmetics:
    allow_custom_suffix: true
    max_suffix_length: 16
    disallowed_colors_in_suffix: true
  limits:
    max_evolve_buys_per_day: 5
    max_xp_buys_per_day: 20
  safety:
    shop_click_cooldown_millis: 250

rules:
  equip_worlds_allow: []
  equip_worlds_deny: []
  leveling_worlds_allow: []
  leveling_worlds_deny: []
  boost_apply_worlds_allow: []
  boost_apply_worlds_deny: []
  disallow_in_spectator: true

auditing:
  enabled: true
  sample_rate: 1.0
  log_dir: "logs"
  rotate_daily: true
  include_breakdown: true

backups:
  enabled: true
  interval_minutes: 60
  keep_files: 24
  file_prefix: "pets-backup-"
  verify_on_load: true

simulator:
  enabled: true
  max_combo_size: 6
  default_types: [earnings_lootfactory, earnings_sell]
  format: { percent_decimals: 0, raw_decimals: 3 }
  async_timeout_seconds: 10
  output_dir: "diagnostics/sim"
  sweep:
    max_points: 2000
    levels: { from: 0, to: 350, step: 10 }
    stars: { from: 0, to: 5, step: 1 }
  tuning:
    search_steps: 24
    per_level_min: 0.001
    per_level_max: 0.03
    star_multiplier_min: 1.10
    star_multiplier_max: 1.60
  safety:
    throttle_millis: 250
    max_console_lines: 200
