default-slots: 2
slot-permission-prefix: "lootpets.slots."
equip-cooldown-ms: 300

leveling_runtime:
  tick_interval_seconds: 30
  xp_per_tick: 1
  xp_per_level: 60
  level_cap_base: 100
  level_cap_extra_per_star: 50

eggs:
  detection:
    strategy: PDC
    namespace: lootpets
    keys:
      type: type
      rarity: rarity
    match:
      name_prefix: "Pet Egg:"
      lore_contains: "LootPets Egg"
  consume_on_redeem: true
  redeem_block_in_creative: false
  redeem_world_blacklist: []
  redeem_cooldown_millis: 300
  sfx:
    unlocked: ""
    duplicate: ""
  messages:
    enabled: true

gui:
  title: "&6Pets"
  rows: 6
  active-slot-indices:
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
  owned-range:
    start: 9
    end: 53
  features:
    filters_enabled: true
    sorting_enabled: true
    pagination_enabled: true
    compare_enabled: true
    album_enabled: true
  pagination:
    page_size: 28
    controls: { prev_slot: 45, next_slot: 53 }
  sorting:
    default: "RARITY_DESC,STARS_DESC,LEVEL_DESC,NAME_ASC"
    modes: [ "RARITY_ASC", "RARITY_DESC", "STARS_ASC", "STARS_DESC", "LEVEL_ASC", "LEVEL_DESC", "NAME_ASC", "NAME_DESC" ]
  filters:
    rarity_filter: true
    type_filter: true
  compare:
    max_items: 2
    open_key: "SHIFT_LEFT_CLICK"

boosts:
  per_level: 0.02
  star_multiplier: 1.5
  max_stars: 5
  stacking_mode: "ADDITIVE"
  rarity_base_multipliers: {}

caps:
  global_multiplier_max: 6.0

placeholders:
  enabled: true
  format:
    percent_decimals: 0
    raw_decimals: 2
    star_symbol: "★"
    list_delimiter: ", "
    colorize_names: true

preview:
  show_types:
    - "earnings_lootfactory"
    - "earnings_sell"
  format_percent: true
  template: "{min} – {max}"
  cap_multiplier: 6.0

permission_tiers:
  enabled: false
  update_interval_seconds: 10
  node_mode: "REPLACE"
  prefix: "lootpets.tier."
  tiers:
    - { min: 1.00, max: 1.10, node: "1" }
    - { min: 1.10, max: 1.25, node: "2" }
    - { min: 1.25, max: 1.50, node: "3" }
    - { min: 1.50, max: 999.0, node: "4" }

album:
  show_unknown_greyed: true
  open_from_pets_gui: true

reload:
  enabled: true

logging:
  verbosity: "INFO"
  debug_categories: [ "papi", "boosts", "eggs", "gui" ]
