name: LootPets
main: com.lootpets.LootPetsPlugin
version: 0.1.0
api-version: '1.21'
softdepend:
  - SpecialItems
commands:
  pets:
    description: Open your pets GUI
    usage: /pets
permissions:
  lootpets.admin:
    default: op
