name: LootPets
main: com.lootpets.LootPetsPlugin
version: 0.5.0
api-version: '1.21'
softdepend:
  - SpecialItems
  - PlaceholderAPI
  - Vault
commands:
  pets:
    description: Open your pets GUI
    usage: /pets
  lootpets:
    description: Admin command for LootPets
    usage: "/lootpets give <player> <petId> | /lootpets reset <player> | /lootpets simulateegg <player> <petId> <rarityId> | /lootpets setlevel <player> <petId> <level> | /lootpets setstars <player> <petId> <stars> | /lootpets calc <player> <type> | /lootpets preview <petId> <rarityId> | /lootpets reload | /lootpets doctor [fix|players|export] | /lootpets audit on|off | /lootpets backup now | /lootpets rules test <player> [type]"
    permission: lootpets.admin
permissions:
  lootpets.admin:
    default: op
