general:
  debug: false
  disabled-worlds: []
  max-broken-blocks: 64
  override_cancelled: true
respawn_seconds: 30
farmxmine:
  direct_to_inventory: true
inventory:
  void_overflow: true
compat:
  veinminer:
    detect_lore: ["Veinminer", "Vein Miner"]
    max_blocks: 64
  harvester:
    max_blocks: 64
leveling:
  xp_per_action:
    MINE_BLOCK_BREAK: 3
    FARM_CROP_BREAK: 1
  per_action_xp_cap: 100
  level_curve:
    base: 50
    exponent: 1.35
bossbar:
  enabled: true
  color: BLUE
  style: SOLID
  timeout_idle_seconds: 10
  timeout_active_seconds: 30
  title_mining: '&6Mining'
  title_farming: '&aFarming'
artifacts:
  enabled: true
  drop_chance_on_levelup_pct: 4.5
  total_unique: 100
  categories: [MINING, FARMING]
  apply_mode: multiplicative
  base_multiplier_common_pct: 1.0
  rarity_weights:
    COMMON: 1.0
  rarity_bonus_pct:
    COMMON: 0.0
  max_total_multiplier_pct: 100.0
