name: FarmxMine
main: com.farmxmine.FarmxMinePlugin
version: 1.0.0
api-version: '1.21'
authors: ['MinehutHelper']
commands:
  artifacts:
    description: View owned artifacts
    usage: /artifacts
  fxm:
    description: FarmxMine admin commands
    permission: farmxmine.admin
    usage: /fxm reload
permissions:
  farmxmine.admin:
    default: op
softdepend: [Vault, PlaceholderAPI, WorldGuard]
