name: FarmxMine
main: com.instancednodes.InstancedNodesPlugin
version: 0.4.6
api-version: '1.21'
authors: [ 'MinehutHelper' ]
commands:
  nodes:
    description: InstancedNodes admin commands
    usage: /nodes <debug|reload>
    permission: instancednodes.admin
  prestige:
    description: Prestige to increase income multiplier
    usage: /prestige
    permission: instancednodes.prestige
permissions:
  instancednodes.admin:
    default: op
  instancednodes.mine:
    default: true
  instancednodes.farm:
    default: true
  instancednodes.prestige:
    default: true
softdepend: [WorldGuard, PlaceholderAPI]
