name: LootFactory
main: com.lootfactory.LootFactoryPlugin
version: 1.0.1
api-version: '1.21'
softdepend: [Vault, EconomyPlus, PlaceholderAPI, LootCrates, LootPets]


commands:
  prestige:
    description: Prestige a factory
    permission: lootfactory.prestige
  factory:
    description: Factory utilities
  factoryshop:
    permission: lootfactory.shop
  factories:
    permission: lootfactory.list

permissions:
  lootfactory.prestige:
    default: true
  lootfactory.admin: { default: op }
  lootfactory.shop: { default: true }
  lootfactory.list: { default: true }
  lootfactory.place: { default: true }
  lootfactory.use: { default: true }
