commands:
  player:
    General:
      - "/home - Teleport to your home"
      - "/spawn - Go to the spawn"
    SpecialItems:
      - "/si - Opens the SpecialItems menu"
    LootFactory:
      - "/lootfactory - Obtain new items from factories" # Placeholder
    LootCrates:
      - "/lootcrates - Open your crates" # Placeholder

  admin:
    General:
      - "/ban <player> - Bans a player"
      - "/kick <player> - Kicks a player"
    FarmXMine:
      - "/nodes <debug|reload> - Manage InstancedNodes"
    SpecialItems:
      - "/bin - Shows deleted SpecialItems"
    LootFactory:
      - "/lootfactoryadmin - Admin commands for LootFactory" # Placeholder
    LootCrates:
      - "/lootcratesadmin - Admin commands for LootCrates" # Placeholder
